#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon May  4 12:40:06 2020

@author: TakahiroKurokawa
"""

#FizzBuzz
def FizzBuzz():
    for i in range(1,101):
        if (i%3==0) & (i%5==0):
           print("FizzBuzz")
        elif i%3==0:
            print("Fizz")
        elif i%5==0:
            print("Buzz")
        else:
            print(i)

a=FizzBuzz()
import random

def linear_search(to_match):
    cards=[]
    for i in range(1,101):
        cards+=[i]
    random.shuffle(cards)
    index=1
    while len(cards)>0:
        a=cards.pop()
        if a==to_match:
            print("{0} is in index{1}".format(to_match,index))
            break
        else:
            print(a)
        index+=1
        
a=linear_search(50)

def rotating_sentence(string):
    string_to_list=list(string)
    while len(string_to_list)>1:
        initial=string_to_list.pop(0)
        end=string_to_list.pop()
        if initial != end:
            return False
            break
    else:
        return True

a=rotating_sentence("BaB")
def palindrom(string):
    string=string.lower()
    return string[::-1]==string

b=palindrom("aba")

def anaglam(string1,string2):
    string1=string1.lower()
    string2=string2.lower()
    return sorted(string1)==sorted(string2)

c=anaglam("anaglam","nagmaal")

from collections import defaultdict
def count_letter(string):
    dic=defaultdict(int)
    string=string.lower()
    string=string.replace(" ","")
    for letter in string:
        dic[letter]+=1
    return dic

a=count_letter("Noriaki Kurokawa")

def bottles_of_beer(bob):
    if bob<1:
        print("No more bottles")
        return
    tmp=bob
    bob-=1
    print("""
          {} bottles of beer on the wall.
          {} bottles of beer.
          Take one down,pass it around,
          {} bottles of beer on the wall.
          """.format(tmp,tmp,bob))
    bottles_of_beer(bob)

a=bottles_of_beer(99)