#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri May  1 10:38:25 2020

@author: TakahiroKurokawa
"""

def function(a):
    """
    入力値を２乗して返す関数です
    """
    return a**2
a=input("input number for 4-1:")
a=int(a)

print(function(a))

def function2(string):
    """
    入力値をそのまま返す関数です
    """
    return string

b=input("input string for 4-2:")
print(function2(b))

def function3(x,y,z,a=1,b=2):
    """
    ３つの位置引数と2つのキーワード引数を受取り演算処理
    """
    return x*y*z+a+b

x=input("input number for 4-3:")
y=input("input number for 4-3:")
z=input("input number for 4-3:")
x=int(x)
y=int(y)
z=int(z)
print(function3(x,y,z))


def function4_1(x):
    """
    入力値を２で割り算、整数部分のみ
    """
    return x//2

def function4_2(y):
    """
    入力値を４倍にして返す関数です
    """
    return y*4

x=input("input number for 4-4:")
x=int(x)
x=function4_1(x)
y=function4_2(x)
print(y)

def function5(string):
    """
    入力値を小数点型（float）にして返す
    """
    return float(string)

try:
    print(function5("A"))
except:
    print("Input data type is not numerical")