#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri May  1 11:05:25 2020

@author: TakahiroKurokawa
"""

favorite_musician=["Aimyon","Mr. Children","King Gnu","Hinatasaka"]
where_i_go=[(136,36),(40.7127,-74.0059)]
my_dic={"feet":173,
        "weight":69,
        "favorite writer":"Higasino Keigo"}
key=input("Input feet or weight or favorite writer:")
print(my_dic[key])

favorite_musician_2={"Aimyon":["Kimi ha Rock nannka kikanai","Ai wo tutaetaidatoka"],
                     "Mr Children":["Mirai","tommorow never knows"],
                     "King Gnu":["Hakujitu","flash"],
                     "Hinatasaka":["Doremirasido","Kyun"]}

print("Set is syuugou")
print("Set can caliculate wasyuugou,sekisyuugou")