#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri May  1 15:23:14 2020

@author: TakahiroKurokawa
"""

with open("example.csv") as f:
    print(f.read())


answer=input("What is your hobby?:")
f=open("answer.txt","w")
f.write(answer)
f.close()

a=[["Top Gun","Risky Bussiness","Minority Report"],
   ["Titanic","The Revenant","Inception"],
   ["Training Day","Man of Fire","Flight"]]

b=[["トップガン","リスキービジネス","マイノリティーレポート"],
   ["タイタニック","ザレベナント","インセプション"],
   ["トレーニングデイ","マンオブファイア","フライト"]]

import csv

with open("movie.csv","w") as f:
    w=csv.writer(f,delimiter=",")
    for i in a:
        w.writerow(i)

with open("movie2.csv","w") as f2:
    w=csv.writer(f2,delimiter=",")
    for i in b:
        w.writerow(i)